walk = "git"

[formatter.nix]
command = "nixfmt"
includes = [ "*.nix" ]

[formatter.lua]
command = "stylua"
includes = [ "*.lua" ]

[formatter.shfmt]
includes = [ "*.sh" ]
command = "shfmt"
options = [ "--write", "--simplify", "--case-indent", "--binary-next-line" ]

# [formatter.shellharden]
# includes = [ "*.sh" ]
# command = "shellharden"
# options = [ "--replace" ]

[formatter.yaml]
includes = [ "*.yaml" ]
command = "yamlfmt"

[formatter.python]
command = "black"
includes = [ "*.py" ]
options = [ "-q" ]
