#!/usr/bin/env bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

signature="Co-Authored-By: Claude <noreply@anthropic.com>" 
commit_msg=$(perl -0777 -pe "s/\n${signature/@/\\@}//g" "$COMMIT_MSG_FILE")

if [ -n "$CLAUDE" ]; then
    if [ -s "$COMMIT_MSG_FILE" ]; then
	printf '%s\n\n%s' "$0 $commit_msg" "$signature" > "$COMMIT_MSG_FILE"
    fi
fi
