[plugin]
preloaders = []

[[plugin.prepend_previewers]]
name = "/media/**"
run = "noop"

[[manager.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- dragon -x -i -T "$1"'

[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[manager]
sort_by = "natural"
